### ISSUE TITLE
Lumber axe won't mine trees.

### ISSUE THREAD

**Issue by toErIpNid** [TeamMFR/MineFantasyReforged#12]
When using a copper lumber axe, the axe wont actually chop down anything. Only making the blocks disappear client side only to reappear upon relog.

**Comment by Xakorik** [comment]
I've had this happen with iron but only with certain MFR trees

**Comment by Pelirow** [comment]
Able to replicate on "wild" world gen trees with various lumber axes. The wood blocks and leaves can be broken upon reload when visible again.

Planted and bonemealed Vanilla, MFR, Explorercraft, and BoP saplings. Lumber axe works properly without the bug for the first three types of saplings. BoP saplings that were planted and bonemealed then hit with a MFR lumber axe consistently reproduced the bug.

**Comment by ThatPolishKid99** [comment]
closed this in 5fb41e0
